/*
 * Copyright 2011 CISIAD, UNED, Spain Licensed under the European Union Public
 * Licence, version 1.1 (EUPL) Unless required by applicable law, this code is
 * distributed on an "AS IS" basis, WITHOUT WARRANTIES OF ANY KIND.
 */
/*
 * To change this template, choose Tools | Templates and open the template in
 * the editor.
 */
/*
 * HillClimberOptionsGUI.java Created on 15-sep-2011, 19:37:32
 */

package org.openmarkov.learning.algorithm.pc.gui;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

import org.openmarkov.core.io.database.CaseDatabase;
import org.openmarkov.core.model.network.ProbNet;
import org.openmarkov.learning.algorithm.pc.PCAlgorithm;
import org.openmarkov.learning.algorithm.pc.independencetester.CrossEntropyIndependenceTester;
import org.openmarkov.learning.core.algorithm.LearningAlgorithm;
import org.openmarkov.learning.gui.AlgorithmConfiguration;
import org.openmarkov.learning.gui.AlgorithmParametersDialog;

/**
 * This abstract class represents the dialog that shows the user the options and
 * parameters of the PC algorithm.
 * @author joliva
 */
@SuppressWarnings("serial")
@AlgorithmConfiguration(algorithm = PCAlgorithm.class)
public class PCParametersDialog extends AlgorithmParametersDialog
{
    /** Implemented independence tester. */
    public static final String[] independenceTesters = {"Entropía cruzada"};
    // Default values for Metric and alpha parameter and degree of accuracy
    private static String        independenceTester  = independenceTesters[0];
    private static String        significanceLevel   = "0.05";
    private static String        alphaParameter      = "0.5";

    /** Creates new form PCOptionsGUI */
    public PCParametersDialog (JFrame parent, boolean modal)
    {
        super (parent, modal);
        setLocationRelativeTo (null);
        initComponents ();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed"
    // desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents ()
    {
        jPanel1 = new javax.swing.JPanel ();
        testerLabel = new javax.swing.JLabel ();
        independenceTesterComboBox = new javax.swing.JComboBox<> ();
        alphaText = new javax.swing.JTextField ();
        jLabel7 = new javax.swing.JLabel ();
        AceptButton = new javax.swing.JButton ();
        jLabel8 = new javax.swing.JLabel ();
        significanceLevelText = new javax.swing.JTextField ();
        setDefaultCloseOperation (javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle (stringDatabase.getString ("Learning.PC.Title"));
        jPanel1.setBorder (javax.swing.BorderFactory.createTitledBorder (stringDatabase.getString ("Learning.PC.Title")));
        testerLabel.setText (stringDatabase.getString ("Learning.PC.IndependenceTest"));
        // independenceTesterComboBox.setModel(new
        // javax.swing.DefaultComboBoxModel(LearningManager.independenceTesters));
        independenceTesterComboBox.addItem (stringDatabase.getString ("Learning.PC.CrossEntropy"));
        alphaText.setText ("0.5");
        jLabel7.setText (stringDatabase.getString ("Learning.Alpha") + ":");
        jLabel7.setToolTipText (stringDatabase.getString ("Learning.Alpha.Tooltip"));
        AceptButton.setText (stringDatabase.getString ("Learning.Ok"));
        AceptButton.addActionListener (new java.awt.event.ActionListener ()
            {
                public void actionPerformed (java.awt.event.ActionEvent evt)
                {
                    AceptButtonActionPerformed (evt);
                }
            });
        jLabel8.setText (stringDatabase.getString ("Learning.PC.SignificanceLevel") + ":");
        jLabel8.setToolTipText (stringDatabase.getString ("Learning.PC.SignificanceLevel.Tooltip"));
        significanceLevelText.setText (significanceLevel);
        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout (jPanel1);
        jPanel1.setLayout (jPanel1Layout);
        jPanel1Layout.setHorizontalGroup (jPanel1Layout.createParallelGroup (javax.swing.GroupLayout.Alignment.LEADING).addGroup (jPanel1Layout.createSequentialGroup ().addGroup (jPanel1Layout.createParallelGroup (javax.swing.GroupLayout.Alignment.LEADING).addGroup (jPanel1Layout.createSequentialGroup ().addContainerGap ().addComponent (testerLabel).addPreferredGap (javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent (independenceTesterComboBox,
                                                                                                                                                                                                                                                                                                                                                                                                                                                   javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                                                                                                                                                                                                                                                                                                   118,
                                                                                                                                                                                                                                                                                                                                                                                                                                                   javax.swing.GroupLayout.PREFERRED_SIZE)).addGroup (jPanel1Layout.createSequentialGroup ().addGap (92,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     92,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     92).addComponent (AceptButton)).addGroup (jPanel1Layout.createSequentialGroup ().addContainerGap ().addGroup (jPanel1Layout.createParallelGroup (javax.swing.GroupLayout.Alignment.LEADING).addComponent (jLabel8).addComponent (jLabel7)).addPreferredGap (javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addGroup (jPanel1Layout.createParallelGroup (javax.swing.GroupLayout.Alignment.TRAILING).addComponent (significanceLevelText,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              40,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              javax.swing.GroupLayout.PREFERRED_SIZE).addComponent (alphaText,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    40,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    javax.swing.GroupLayout.PREFERRED_SIZE)))).addContainerGap (12,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Short.MAX_VALUE)));
        jPanel1Layout.setVerticalGroup (jPanel1Layout.createParallelGroup (javax.swing.GroupLayout.Alignment.LEADING).addGroup (jPanel1Layout.createSequentialGroup ().addGap (18,
                                                                                                                                                                               18,
                                                                                                                                                                               18).addGroup (jPanel1Layout.createParallelGroup (javax.swing.GroupLayout.Alignment.BASELINE).addComponent (independenceTesterComboBox,
                                                                                                                                                                                                                                                                                          javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                                                                                                                                          javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                                                                                                                                          javax.swing.GroupLayout.PREFERRED_SIZE).addComponent (testerLabel)).addPreferredGap (javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                                                                                                                                                                                                                                                                                               15,
                                                                                                                                                                                                                                                                                                                                                                               Short.MAX_VALUE).addGroup (jPanel1Layout.createParallelGroup (javax.swing.GroupLayout.Alignment.BASELINE).addComponent (jLabel8).addComponent (significanceLevelText,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              javax.swing.GroupLayout.PREFERRED_SIZE)).addPreferredGap (javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addGroup (jPanel1Layout.createParallelGroup (javax.swing.GroupLayout.Alignment.BASELINE).addComponent (jLabel7).addComponent (alphaText,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            javax.swing.GroupLayout.PREFERRED_SIZE)).addGap (11,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             11,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             11).addComponent (AceptButton).addContainerGap ()));
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout (getContentPane ());
        getContentPane ().setLayout (layout);
        layout.setHorizontalGroup (layout.createParallelGroup (javax.swing.GroupLayout.Alignment.LEADING).addGroup (layout.createSequentialGroup ().addContainerGap ().addComponent (jPanel1,
                                                                                                                                                                                     javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                                     javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                                     javax.swing.GroupLayout.PREFERRED_SIZE).addContainerGap (javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                                                                                              Short.MAX_VALUE)));
        layout.setVerticalGroup (layout.createParallelGroup (javax.swing.GroupLayout.Alignment.LEADING).addGroup (layout.createSequentialGroup ().addContainerGap ().addComponent (jPanel1,
                                                                                                                                                                                   javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                                                                                   javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                                   javax.swing.GroupLayout.PREFERRED_SIZE).addContainerGap (javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                                                                                                            Short.MAX_VALUE)));
        pack ();
    }// </editor-fold>//GEN-END:initComponents

    private void AceptButtonActionPerformed (java.awt.event.ActionEvent evt)
    {// GEN-FIRST:event_AceptButtonActionPerformed
        try
        {
            double alpha = Double.parseDouble (alphaText.getText ());
            double degreeAcc = Double.parseDouble (significanceLevelText.getText ());
            if ((alpha < 0) || (alpha > 1) || (degreeAcc < 0) || (degreeAcc > 1))
            {
                JOptionPane.showMessageDialog (null,
                                               stringDatabase.getString ("Learning.PC.IncorrectParameter"),
                                               stringDatabase.getString ("ErrorWindow.Title.Label"),
                                               JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
        catch (NumberFormatException e)
        {
            JOptionPane.showMessageDialog (null,
                                           stringDatabase.getString ("Learning.PC.IncorrectParameter"),
                                           stringDatabase.getString ("ErrorWindow.Title.Label"),
                                           JOptionPane.ERROR_MESSAGE);
            return;
        }
        independenceTester = independenceTesterComboBox.getSelectedItem ().toString ();
        significanceLevel = significanceLevelText.getText ();
        alphaParameter = alphaText.getText ();
        this.setVisible (false);
    }// GEN-LAST:event_AceptButtonActionPerformed

    public String getDescription ()
    {
        return stringDatabase.getString ("Learning.PC.IndependenceTest.Short") + ": "
               + independenceTesterComboBox.getSelectedItem () + "\r\n"
               + stringDatabase.getString ("Learning.PC.SignificanceLevel") + ": "
               + significanceLevel + "\r\n" + stringDatabase.getString ("Learning.Alpha") + ": "
               + alphaParameter;
    }

    public String getIndependenceTester ()
    {
        return independenceTester;
    }

    public String getDegreeOfAccuracy ()
    {
        return significanceLevel;
    }

    public String getAlphaParameter ()
    {
        return alphaParameter;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton           AceptButton;
    private javax.swing.JLabel            testerLabel;
    private javax.swing.JTextField        significanceLevelText;
    private javax.swing.JTextField        alphaText;
    private javax.swing.JLabel            jLabel7;
    private javax.swing.JLabel            jLabel8;
    private javax.swing.JPanel            jPanel1;
    private javax.swing.JComboBox<String> independenceTesterComboBox;

    // End of variables declaration//GEN-END:variables

    @Override
    public LearningAlgorithm getInstance (ProbNet probNet, CaseDatabase database)
    {
        return new PCAlgorithm (probNet, database, Double.parseDouble (alphaParameter),
                                new CrossEntropyIndependenceTester (),
                                Double.parseDouble (significanceLevel));
    }
}
